### ISSUE TITLE
Menu and Search Bar

### ISSUE THREAD

**Issue by wyu** [cmap/morpheus.R#1]
Thanks for the wonderful package! I'm particular interested in the potential to handle very large heatmap such as that of TCGA as you've demonstrated. 

One thing I wish is the ability to turn of the display of menu and search bar on the top of view. It'd blend in much better with the rest of my Shiny app. 

Thanks!

**Comment by joshua-gould** [comment]
You can remove the menu and toolbar as follows:
morpheus( menu=list(), toolbar=c()}
