### ISSUE TITLE
why last column annotation show balck color when you show color.

### ISSUE THREAD

**Issue by yubau1112** [cmap/morpheus.R#11]
original

![image](https://user-images.githubusercontent.com/45645173/159504529-a3716fd9-b38a-4fdf-840f-9e22e0333078.png)

add color
![image](https://user-images.githubusercontent.com/45645173/159502933-5d5bfec6-1a50-4291-9ae1-0af117c4442e.png)

but out put svg file is 

![image](https://user-images.githubusercontent.com/45645173/159503773-cabb1434-4f59-485b-97e4-aa456faeb469.png)
I only push a buttom 'show color'

![image](https://user-images.githubusercontent.com/45645173/159503308-951db2cd-4e36-44a2-9556-63a5c3a70aa5.png)

and output svg file

thanks 

yubau

**Comment by joshua-gould** [comment]
Can you please try saving the image as png? Does the issue persist? Thanks.

**Comment by yubau1112** [comment]
@joshua-gould 

Thanks for your quick reply.
This problem doesn't happen if I save to png file format, but I need SVG format for high-resolution output.
I use the web page or Rstudio always have this problem.

Thanks!
yubau

**Comment by joshua-gould** [comment]
What about saving as pdf?

**Comment by yubau1112** [comment]
pdf does not have the problem

better than svg and png but
If there are too many color legends, it will go beyond the right border and the legend will not be visible.

Will this problem be updated in the near future?

Thank you

**Comment by yubau1112** [comment]
thank for your reply.
