### ISSUE TITLE
Clearing Morpheus Plot Area

### ISSUE THREAD

**Issue by versipellis** [cmap/morpheus.R#2]
Awesome package - thanks a lot!

I have an eventReactive function set up for rendering the Morpheus plot when the user presses a button in this manner:

```
server <- function(input, output) {

  funcPlot <- eventReactive(input$pressRender, {
        
    morpheus(data,
             symm = TRUE,
             dendrogram = "both",
             rowSize = 'fit',
             columnSize = 'fit',
             drawGrid = 'false',
             gridThickness = 0.01)
  })
  
  output$heatmapPlot <- renderMorpheus({
    funcPlot()
  })
```

It's set up in this manner as I've a bunch of other UI pages for doing some calculations and data input/cleaning that the Morpheus UI alone can't handle. The problem is each time the user hits the "Render" button, it generates a new Morpheus plot below the existing one. Is there a way to clear the existing plot area before rendering the new Morpheus plot?

**Comment by mfazel** [comment]
I had the same problem, but really did not spent time to solve it.

Mehdi

**Comment by joshua-gould** [comment]
I just pushed a change that fixes this issue. Please let me know if you run into any problems.
