### ISSUE TITLE
Analogous heatmap.2 breaks argument in morpheus?

### ISSUE THREAD

**Issue by versipellis** [cmap/morpheus.R#3]
I'm converting some plots from heatmap.2 to morpheus, and was wondering if there was an analogous argument in morpheus for the breaks argument in heatmap.2 that allows you to provide a numeric vector for splitting and binning values into colors. It seems like you can achieve something close to that by adding color stops, but if you have a scale like viridis you'd need to interpolate what the color should be for a given breakpoint rather than the heatmap doing it automatically.

**Comment by joshua-gould** [comment]
You currently need to do the interpolation yourself.
